# Generated by Django 5.0.3 on 2024-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_usercoursecontentprogress_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
    ]
