# Generated by Django 5.0.3 on 2024-04-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_utlis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(upload_to='course_files/'),
        ),
    ]
